### PR TITLE
Add standalone ceres-maintenance and plugins

### PR DESCRIPTION
**Pull request by iain-buclaw-sociomantic**
For now, I've made this purposely not carbon-aware.  The original support for megacarbon branch won't work with carbon master,  and none of the existing plugins use anything from carbon anyway.

See https://github.com/graphite-project/carbon/pull/596

FYI @obfuscurity

### CODE REVIEW

**Comment by obfuscurity** [comment]
Awesome. I haven't run Ceres much myself, do you have any documentation we could add to the official docs?

**Comment by iain-buclaw-sociomantic** [comment]
@obfuscurity - I do not at hand, but I could write something up.  How technical do you expect these to be? From: I'm a user who just wants something to work, to: I'm interested in the internal layout of the data and mechanisms.

**Comment by obfuscurity** [comment]
Very high level. Basically something along the lines of http://graphite.readthedocs.io/en/latest/admin-carbon.html but with a brief explanation / usage example for each tool. It would be awesome to have something like http://graphite.readthedocs.io/en/latest/whisper.html for Ceres, but first thing's first.

**Comment by iain-buclaw-sociomantic** [comment]
Documentation for carbon: https://github.com/graphite-project/carbon/pull/603
Graphite documentation (just a primer for the moment): https://github.com/graphite-project/graphite-web/pull/1719

**Comment by obfuscurity** [comment]
@mleinart I was waiting to see the docs go in first, but it's NBD. Thanks @iain-buclaw-sociomantic for the contribution!

**Comment by iain-buclaw-sociomantic** [comment]
Thanks. :-)

**Pull request merged**
